export const clerkAppearance = {
  variables: {
    colorPrimary: "#171717",
    colorText: "#171717",
    colorTextSecondary: "#6b7280",
    colorBackground: "#ffffff",
    colorInputBackground: "#ffffff",
    colorInputText: "#171717",
    borderRadius: "0.5rem",
    fontSize: "0.875rem",
  },
  elements: {
    rootBox: "w-full",
    card: "shadow-none border-0 p-0 bg-transparent w-full gap-0",
    cardBox: "shadow-none border-0",
    header: "hidden",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    socialButtons: "grid grid-cols-2 gap-3 w-full",
    socialButtonsBlockButton:
      "border border-gray-200 rounded-lg bg-white hover:bg-gray-50 text-gray-900 font-normal shadow-none h-11 [&>span]:gap-2",
    socialButtonsBlockButtonText: "font-medium text-sm",
    socialButtonsProviderIcon: "size-5",
    dividerRow: "my-6",
    dividerLine: "bg-gray-200",
    dividerText: "text-gray-400 text-sm lowercase",
    form: "gap-4",
    formFieldRow: "gap-1.5",
    formFieldLabel: "text-sm font-semibold text-gray-900",
    formFieldInput:
      "border border-gray-200 rounded-lg h-11 text-sm shadow-none focus:ring-2 focus:ring-gray-900/10 focus:border-gray-300",
    formButtonPrimary:
      "bg-gray-900 hover:bg-gray-800 rounded-lg h-11 text-sm font-medium shadow-none normal-case",
    formButtonPrimaryIcon: "size-3.5",
    footer: "hidden",
    footerAction: "hidden",
    footerActionLink: "hidden",
    identityPreview: "hidden",
    identityPreviewEditButton: "hidden",
    formFieldInputShowPasswordButton: "text-gray-500",
    alert: "rounded-lg",
    otpCodeFieldInput: "border border-gray-200 rounded-lg h-11",
    formResendCodeLink: "text-gray-900",
    backLink: "text-gray-600 hover:text-gray-900",
    navbar: "hidden",
    logoBox: "hidden",
    main: "gap-0",
  },
};
